ThesisProject.WebApp/Controllers/DoctorsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using ThesisProject.Data.Domain;
using ThesisProject.Data.Services;
using ThesisProject.WebApp.Models.Doctors;
using ThesisProject.WebApp.Models.Stats;

namespace ThesisProject.WebApp.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly ILogger<UsersController> _logger;
        private readonly IDoctorService _doctorService;
        private readonly IStatsService _statsService;
        private readonly UserManager<AppUser> _userManager;

        public DoctorsController(ILogger<UsersController> logger, IDoctorService doctorService, IStatsService statsService, UserManager<AppUser> userManager)
        {
            _logger = logger;
            _doctorService = doctorService;
            _statsService = statsService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var vm = new DoctorSearchViewModel();
            vm.Branches = await _doctorService.GetBranches().Select(x => x.Name).ToListAsync();
            vm.Specialities = await _doctorService.GetSpecialities().Select(x => x.Name).ToListAsync();
            vm.Doctors = await _doctorService.GetDoctors().ToListAsync();
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Index(DoctorSearchViewModel viewModel)
        {
            viewModel.Branches = await _doctorService.GetBranches().Select(x => x.Name).ToListAsync();
            viewModel.Specialities = await _doctorService.GetSpecialities().Select(x => x.Name).ToListAsync();
            viewModel.Doctors = await _doctorService.GetDoctors(viewModel.Name, viewModel.Speciality, viewModel.Branch).ToListAsync();
            return View(viewModel);
        }
        public async Task<IActionResult> Details(string id, string returnUrl)
        {
            var doc = await _doctorService.GetDoctorByIdAsync(id);
            var vm = new DetailsDoctorViewModel
            {
                Doctor = doc,
                ReturnUrl = returnUrl
            };
            return View(vm);
        }
        public async Task<IActionResult> Edit(string Id, string returnUrl)
        {
            var vm = new DoctorEditViewModel();
            vm.ReturnUrl = returnUrl;
            var doc = await _doctorService.GetDoctorByIdAsync(Id);
            var specs = await _doctorService.GetSpecialities()
                    .Select(x => x.Name).ToListAsync();
            var branches = await _doctorService.GetBranches()
                .Select(x => x.Name).ToListAsync();
            vm.EditModel = new Models.User.EditUserViewModel(doc, "Doctor", branches, specs);
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(DoctorEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);
            var docModel = viewModel.EditModel;
            await _doctorService.UpdateAsync(docModel.Id, docModel.Name1, docModel.Name2,
                    docModel.Name3, docModel.Branch, docModel.Speciality, docModel.ContactEmail,
                    docModel.ContactPhoneNumber, docModel.CabinetNumber);
            if(!string.IsNullOrEmpty(viewModel.ReturnUrl))
            {
                return LocalRedirect(viewModel.ReturnUrl);
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Stats(string Id, string returnUrl)
        {
            if (string.IsNullOrEmpty(Id))
                Id = _userManager.GetUserId(User);
            var now = DateTime.Now;
            var vm = new DoctorStatsViewModel()
            {
                Start = new DateTime(now.Year, now.Month, 1),
                End = now.Date,
                ReturnUrl = returnUrl
            };
            vm.Stats = await _statsService.GetDoctorStats(Id, vm.Start, vm.End);
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Stats(DoctorStatsViewModel viewModel)
        {
            viewModel.Stats = await _statsService.GetDoctorStats(viewModel.Id,
                viewModel.Start, viewModel.End);
            return View(viewModel);
        }
    }
}

ThesisProject.WebApp/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThesisProject.Data.Domain;
using ThesisProject.Data.Services;

namespace ThesisProject.WebApp.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IServicesService _servicesService;

        public ServicesController(IServicesService servicesService)
        {
            _servicesService = servicesService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Vaccinations()
        {
            var vaccinations = await _servicesService.GetVaccinations(false).ToArrayAsync();
            return View(vaccinations);
        }
        public ActionResult AddVaccination()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddVaccination(Vaccination vaccination)
        {
            if (!ModelState.IsValid)
                return View(vaccination);
            try
            {
                vaccination.Date = DateTime.Now.Date;
                vaccination.IsActive = true;
                await _servicesService.AddVaccination(vaccination);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(vaccination);
            }
            return RedirectToAction(nameof(Vaccinations));
        }
    }
}

ThesisProject.WebApp/Controllers/StatsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using ThesisProject.Data.Domain;
using ThesisProject.Data.Services;
using ThesisProject.WebApp.Models.Stats;

namespace ThesisProject.WebApp.Controllers
{
    public class StatsController : Controller
    {
        private readonly ILogger<UsersController> _logger;
        private readonly IStatsService _statsService;
        private readonly UserManager<AppUser> _userManager;

        public StatsController(ILogger<UsersController> logger, IStatsService statsService, UserManager<AppUser> userManager)
        {
            _logger = logger;
            _statsService = statsService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> DiagnoseStats(string returnUrl)
        {
            var now = DateTime.Now;
            var vm = new DiagnoseStatsViewModel
            {
                Start = new DateTime(now.Year, now.Month, 1),
                End = now.Date,
                ReturnUrl = returnUrl
            };
            vm.Stats = await _statsService.GetIssueStats(vm.Start, vm.End);
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DiagnoseStats(DiagnoseStatsViewModel viewModel)
        {
            viewModel.Stats = await _statsService.GetIssueStats(viewModel.Start, viewModel.End);
            return View(viewModel);
        }

    }
}

ThesisProject.WebApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Data;
using ThesisProject.Data.Services;
using ThesisProject.Data.Domain;
using ThesisProject.Data;
using Microsoft.AspNetCore.Authorization;
using System.Linq.Dynamic.Core;
using System.Threading;
using ThesisProject.WebApp.Models.User;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;
using ThesisProject.WebApp.Models.AddressModels;
using ThesisProject.WebApp.Models.Home;

namespace ThesisProject.WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IIdentityService _identityService;
        private readonly IUserStore<AppUser> _userStore;
        private readonly AppDbContext _dbContext;
        private ILogger<UsersController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IDoctorService _doctorService;
        private readonly IUserService _userService;

        public UsersController(IIdentityService identityService, IUserStore<AppUser> userStore,
            AppDbContext dbContext, ILogger<UsersController> logger, UserManager<AppUser> userManager,
            RoleManager<IdentityRole> roleManager, SignInManager<AppUser> signInManager,
            IDoctorService doctorService, IUserService userService)
        {
            _identityService = identityService;
            _userStore = userStore;
            _dbContext = dbContext;
            _logger = logger;
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _doctorService = doctorService;
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> LoadUsers()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                var start = HttpContext.Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault()
                    + "][name]"].FirstOrDefault();

                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                var pageSize = length != null ? Convert.ToInt32(length) : 0;
                var skip = start != null ? Convert.ToInt32(start) : 0;

                var recordsTotal = 0;

                var data = _identityService.GetUsers();

                var debugg = await data.ToListAsync();

                if (!(string.IsNullOrEmpty(sortColumn)) && !(string.IsNullOrEmpty(sortColumnDirection)))
                {
                    data = data.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                if (!string.IsNullOrEmpty(searchValue))
                {
                    data = data.Where(m => (m.Email.Contains(searchValue) || m.Role.Contains(searchValue)));
                }

                recordsTotal = data.Count();

                var result = await data.Skip(skip).Take(pageSize).ToListAsync();
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = result });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(ex.Message);
                Console.ResetColor();
                throw;
            }
        }
        public async Task<IActionResult> Create(string returnUrl = null)
        {
            var vm = new CreateUserModel { ReturnUrl = returnUrl };
            vm.Roles = await GetRoles();

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserModel viewModel)
        {
            viewModel.ReturnUrl ??= Url.Content("~/");
            if(ModelState.IsValid)
            {
                IdentityResult identityResult = null;
                if (viewModel.Role == "Admin")
                    identityResult = await _identityService.CreateUser<AppUser>(viewModel.Email, viewModel.Password, viewModel.Role);
                else if (viewModel.Role == "Doctor")
                    identityResult = await _identityService.CreateUser<Doctor>(viewModel.Email, viewModel.Password, viewModel.Role);
                else if (viewModel.Role == "Pacient")
                    identityResult = await _identityService.CreateUser<Pacient>(viewModel.Email, viewModel.Password, viewModel.Role);
                if (identityResult.Succeeded)
                {
                    return LocalRedirect(viewModel.ReturnUrl);
                }
                viewModel.Roles = await GetRoles();
                foreach (var error in identityResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(viewModel);
        }
        public async Task<IActionResult> Edit(string Id, string returnUrl)
        {
            var user = await _userManager.FindByIdAsync(Id);
            var role = (await _userManager.GetRolesAsync(user)).FirstOrDefault();
            EditUserViewModel vm = null;
            if(role == "Admin")
            {
                vm = new EditUserViewModel(user, role);
            }
            if(role == "Doctor")
            {
                var doc = await _doctorService.GetDoctorByIdAsync(Id);
                var specs = await _doctorService.GetSpecialities()
                    .Select(x => x.Name).ToListAsync();
                var branches = await _doctorService.GetBranches()
                    .Select(x => x.Name).ToListAsync();
                vm = new EditUserViewModel(doc, role, branches, specs);
                vm.returnUrl = returnUrl;
            }
            if (!(role == "Pacient"))
                return View(vm);
            return RedirectToAction("Edit", "Pacients", new {id = Id, returnUrl = returnUrl});
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);
            
            if (viewModel.Role == "Admin")
            {
                var user = await _userManager.FindByIdAsync(viewModel.Id);

                user.Name1 = viewModel.Name1;
                user.Name2 = viewModel.Name2;
                user.Name3 = viewModel.Name3;

                var result = await _userStore.UpdateAsync(user, CancellationToken.None);
                if (!result.Succeeded)
                {
                    foreach(var e in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, e.Description);
                    }
                    return View(viewModel);
                }
            }
            if(viewModel.Role == "Doctor")
            {
                await _doctorService.UpdateAsync(viewModel.Id, viewModel.Name1, viewModel.Name2,
                    viewModel.Name3, viewModel.Branch, viewModel.Speciality, viewModel.ContactEmail,
                    viewModel.ContactPhoneNumber, viewModel.CabinetNumber);
            }
            if (!string.IsNullOrEmpty(viewModel.returnUrl))
                return LocalRedirect(viewModel.returnUrl);
            return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        public async Task<IActionResult> ChangeSchedule(string id, string returnUrl)
        {
            if (string.IsNullOrEmpty(id))
                id = _userManager.GetUserId(User);
            var viewModel = new ChangeScheduleViewModel
            {
                ReturnUrl = returnUrl,
                DoctorId = id
            };
            viewModel.Schedules = await _doctorService.GetScheduleByDocId(id).ToArrayAsync();
            viewModel.Doctor = await _doctorService.GetDoctorByIdAsync(id);
            return View(viewModel);
        }
        public async Task<IActionResult> AddSchedule(string docId, Schedule schedule, string returnUrl)
        {
            await _doctorService.AddToSchedules(docId, schedule);
            return RedirectToAction(nameof(ChangeSchedule), new { id = docId, returnUrl = returnUrl });
        }
        public async Task<IActionResult> EditSchedule(int id, string docId, string returnUrl)
        {
            var vm = new EditScheduleViewModel
            {
                DocId = docId,
                returnUrl = returnUrl,
                Schedule = await _doctorService.GetScheduleById(id)
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> EditSchedule(EditScheduleViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            await _doctorService.UpdateSchedule(viewModel.Schedule);
            return LocalRedirect(viewModel.returnUrl);
        }
        public async Task<IActionResult> DeleteSchedule(int id, string docId, string returnUrl)
        {
            await _doctorService.DeleteScheduleAsync(id);
            return RedirectToAction(nameof(ChangeSchedule), new { id = docId, returnUrl = returnUrl });
        }
        public async Task<IActionResult> Remove(string Id)
        {

ThesisProject.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThesisProject.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/datatables/css/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="~/datatables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/fullcalendar/main.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Диплом</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Услуги</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Stats" asp-action="Index">Статистика</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || User.IsInRole("Pacient"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">Доктора</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || User.IsInRole("Doctor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pacients" asp-action="Index">Пациенты</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ThesisProject.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ThesisProject.WebApp/Views/Shared/_StatusMessage.cshtml
@model StatusModel

@if (!String.IsNullOrEmpty(Model.StatusMessage))
{
    var statusMessageClass = Model.IsError ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model.StatusMessage
    </div>
}